import json
import logging
from pathlib import Path
import sys
import time
from typing import Any, Dict, List, Optional, Tuple, Union

from docling.chunking import HybridChunker
from docling.datamodel.base_models import InputFormat
from docling.datamodel.document import DoclingDocument
from docling.datamodel.pipeline_options import PdfPipelineOptions
from docling.document_converter import (
    DocumentConverter,
    ImageFormatOption,
    PdfFormatOption,
)
from docling_ocr_onnxtr import OnnxtrOcrOptions

from components.embedding.component import EmbeddingComponent

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
)
logger = logging.getLogger("DoclingOnnxTR")


def create_document_converter(
    force_full_page_ocr: bool = False,
) -> DocumentConverter:
    """Create and configure a Docling DocumentConverter using the OnnxTR OCR engine."""
    pipeline_options = PdfPipelineOptions()
    pipeline_options.do_ocr = True
    pipeline_options.allow_external_plugins = True
    pipeline_options.ocr_options = OnnxtrOcrOptions(
        force_full_page_ocr=force_full_page_ocr
    )

    format_options = {
        InputFormat.PDF: PdfFormatOption(pipeline_options=pipeline_options),
        InputFormat.IMAGE: ImageFormatOption(pipeline_options=pipeline_options),
    }

    return DocumentConverter(format_options=format_options)


def create_chunker() -> HybridChunker:
    """Create and configure a Docling HybridChunker."""
    return HybridChunker()


def chunk_and_embed_document(
    doc: DoclingDocument,
    file_id: str,
    embedder: Optional[EmbeddingComponent] = None,
    chunker: Optional[HybridChunker] = None,
    ocr_engine_name: str = "OnnxTR",
    is_ocr: bool = True,
) -> List[Dict[str, Any]]:
    """
    Chunk a DoclingDocument using HybridChunker and generate embeddings for each chunk.

    Each chunk contains:
    - chunk_id: index of the chunk
    - file_id: identifier of the source file
    - page_number: primary (first) page number of the chunk
    - page_numbers: list of all page numbers spanned by the chunk
    - ocr_text: the chunk text extracted via OCR / Docling
    - is_ocr: flag indicating the text was processed by OCR
    - ocr_engine: name of the OCR engine used (e.g., 'OnnxTR')
    - embedding: vector embedding generated by EmbeddingComponent
    - embedding_metadata: metadata about the embedding model and execution timing
    """
    if chunker is None:
        chunker = create_chunker()

    if embedder is None:
        embedder = EmbeddingComponent()

    raw_chunks = list(chunker.chunk(doc))
    embedded_chunks: List[Dict[str, Any]] = []

    for idx, chunk in enumerate(raw_chunks):
        chunk_text = chunk.text
        if not chunk_text or not chunk_text.strip():
            continue

        # Extract page numbers from provenance items in doc_items
        page_set = set()
        for item in getattr(chunk.meta, "doc_items", []):
            for prov in getattr(item, "prov", []):
                if hasattr(prov, "page_no") and prov.page_no is not None:
                    page_set.add(int(prov.page_no))

        page_numbers = sorted(list(page_set))
        if not page_numbers and doc.pages:
            page_numbers = [min(doc.pages.keys())]
        elif not page_numbers:
            page_numbers = [1]

        primary_page = page_numbers[0]

        # Generate embedding and time it
        start_time = time.time()
        embedding_vector = embedder.embed_text(chunk_text)
        exec_time_ms = (time.time() - start_time) * 1000.0

        embedding_meta = embedder.get_metadata(
            file_path=file_id,
            execution_time_ms=exec_time_ms,
        )

        chunk_record: Dict[str, Any] = {
            "chunk_id": idx,
            "file_id": file_id,
            "page_number": primary_page,
            "page_numbers": page_numbers,
            "ocr_text": chunk_text,
            "is_ocr": is_ocr,
            "ocr_engine": ocr_engine_name,
            "embedding": embedding_vector,
            "embedding_metadata": embedding_meta,
        }
        embedded_chunks.append(chunk_record)

    return embedded_chunks


def save_chunks_to_json(
    chunks: List[Dict[str, Any]],
    output_path: Union[str, Path],
) -> Path:
    """Save the list of embedded chunks to a JSON file."""
    out_file = Path(output_path)
    out_file.parent.mkdir(parents=True, exist_ok=True)
    with open(out_file, "w", encoding="utf-8") as f:
        json.dump(chunks, f, indent=2, ensure_ascii=False)
    return out_file


def process_document(
    input_path: Union[str, Path],
    output_json_path: Optional[Union[str, Path]] = None,
    force_full_page_ocr: bool = False,
    embedder: Optional[EmbeddingComponent] = None,
) -> Tuple[DoclingDocument, List[Dict[str, Any]]]:
    """
    Process a document with Docling using OnnxTR OCR, chunk it, generate embeddings,
    and save the embedded chunks to a JSON file.
    """
    input_file = Path(input_path)
    if not input_file.exists():
        raise FileNotFoundError(f"Document not found: {input_file}")

    file_id = input_file.name

    logger.info(f"Converting document '{input_file}' with Docling + OnnxTR OCR...")
    converter = create_document_converter(force_full_page_ocr=force_full_page_ocr)
    conv_res = converter.convert(input_file)
    doc: DoclingDocument = conv_res.document

    logger.info("Chunking document and generating OpenCLIP embeddings...")
    chunks = chunk_and_embed_document(
        doc=doc,
        file_id=file_id,
        embedder=embedder,
    )

    if output_json_path is not None:
        out_file = Path(output_json_path)
        if out_file.is_dir():
            out_file = out_file / f"{input_file.stem}.chunks.json"
        save_chunks_to_json(chunks, out_file)
        logger.info(f"Saved {len(chunks)} chunks to: {out_file}")

    return doc, chunks


def main() -> None:
    if len(sys.argv) < 2:
        print("Usage: python docling_onnxtr.py <path_to_document> [output_json_path]")
        return

    doc_path = Path(sys.argv[1])
    out_json_path = (
        Path(sys.argv[2])
        if len(sys.argv) > 2
        else doc_path.with_name(f"{doc_path.stem}.chunks.json")
    )

    print(f"Processing '{doc_path}' using OnnxTR OCR and generating embeddings...")
    doc, chunks = process_document(doc_path, output_json_path=out_json_path)

    print(f"Successfully processed: {doc.name}")
    print(f"Total pages: {len(doc.pages)}")
    print(f"Total chunks created & embedded: {len(chunks)}")
    print(f"Saved chunks to: {out_json_path}")


if __name__ == "__main__":
    main()
